[window]
option_as_alt = "Both"   # Treats both left and right Option keys as Alt (for bindings)
# Alternatives:
# - "OnlyLeft"  (left Option = Alt; right = normal chars like €, ≈)
# - "OnlyRight" (opposite)
# - "None"      (default: normal macOS Option behavior)

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 9.0

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"

[font.normal]
family = "Iosevka Term"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Control"

#[[keyboard.bindings]]
#action = "CreateNewWindow"
#key = "N"
#mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Option"

# disable macos window close to prevent accidentally closing unsaved documents
[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

# disable macos window close to prevent accidentally closing unsaved documents
[[keyboard.bindings]]
action = "None"
key = "q"
mods = "Command"

[general]
#import = ["/home/kennyw/.config/alacritty/themes/hardhacker.toml"]
import = ["/Users/kennywoo/.config/alacritty/themes/hardhacker.toml"]
